---
title: "Paragraphs"
author: "Sam Tyner"
date: "6/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Source: [CVL Database](https://cvl.tuwien.ac.at/research/cvl-databases/an-off-line-database-for-writer-retrieval-writer-identification-and-word-spotting/)

The following are the texts that the 6 documents were created from: 

# Doc 1 

"Imagine a vast sheet of paper on which straight Lines, Triangles, Squares, Pentagons, Hexagons, and other figures, instead of remaining fixed in their places, move freely about, on or in the surface, but without the power of rising above or sinking below it, very much like shadows -- only hard with luminous edges -- and you will then have a pretty correct notion of my country and countrymen. Alas, a few years ago, I should have said "my universe": but now my mind has been opened to higher views of things." 

# Doc 2 

"And Fortune, on his damned quarrel smiling,
Showed like a rebel's whore. But all's too weak;
For brave Nomacs - well he deserves that name -
Disdaining Fortune, with his brandished steel,
Which smoked with bloody execution,
Like valor's minion, carved out his passage
Till he faced the slave;"

# Doc 3 

"Mailüfterl is an Austrian nickname for the first computer working solely on transistors on the European mainland. It was built in 1955 at the Venna University of Technology by Heinz Zemanek. The builder plays on a quote on an operating computer: "If it is not the rapid calulation speed of American models that Whirlwind or Typhoon can achieve, it will be enough for a Wiener Mailüfterl". The full name is Binär dezimaler Volltransistor-Rechenautomat."

# Doc 4 

"When we look to the individuals of the same variety or sub-variety of our older cultivated plants and animals, one of the first points which strikes us, is, that they generally differ much more from each other, than do the individuals of any one species or variety in a state of nature. "

# Doc 7  

"You have killed my love. You used to stir my imagination. Now you don't even stir my curiosity. You simply produce no effect. I loved you because you were marvelous, because you had genius and intellect, because you realized the dreams of great poets and gave shape and substance to the shadows of art. You have thrown it all away. You are shallow and stupid"

# Doc 8

"While I gazed, this fissure rapidly widened -- there came a fierce breath of the whirlwind -- the entire orb of the satellite burst at once upon my sight -- my brain reeled as I saw the mighty walls rushing asunder -- there was a long tumultuous shouting sound like the voice of a thousand waters -- and the deep and dank tarn at my feet close sullenly and silently over the fragments of the "House of Usher." 




